
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Run all tests
        run: bazel test --config=_gcc :all
